### ISSUE TITLE
Update setup files to support parameter sweeps

### ISSUE THREAD

**Issue by jessicasyu** [bagherilab/ARCADE#127]
Copying thread from PR for posterity. It sounds like this isn't a high priority feature, and that we would need to do some thinking about implementation. I vote to mark as `priority: low` and `status: on the roadmap` and then revisit if there is more interest? Or, we can close as `status: out of scope`. @allison-li-1016? @cainja?

---

> It would be helpful to include an example/explanation for how to set up multiple series.
>
> This relates to a conversation with @cainja where someone mentioned having the equivalent of running a bunch of simulations where we go through a list of parameter values for one parameter, and if there was a way to do that non-manually. I think this feature will be relevant for people who use the model to see how changing the range of a parameter affects the resulting behavior.

_Originally posted by @allison-li-1016 in https://github.com/bagherilab/ARCADE/pull/119#discussion_r1879080592_
            
> The current non-manual way to do parameter sweeps would be to set up a template setup file and then populate it with parameter values using something like Jinja (see the [run batch simulations flow](https://github.com/allen-cell-animated/cell-abm-pipeline/blob/main/src/cell_abm_pipeline/flows/run_batch_simulations.py) for a pipeline example).
> 
> I'm not sure that ARCADE itself should support something like `<population.parameter id="A" value="(1|2|3)" />`. It would be straightforward for a single parameter, but I think parsing would get a lot more complex if multiple parameters are changed. For example, for something like:
> 
> ```
> <population.parameter id="A" value="(1|2|3)" />
> <population.parameter id="B" value="(4|5|6)" />
> ```
> 
> would this is be 3 or 9 combinations? We should probably move this to an issue. @cainja?

_Originally posted by @jessicasyu in https://github.com/bagherilab/ARCADE/pull/119#discussion_r1880569013_

> I don't necessarily think this approach itself needs to be a feature - many other libraries do sensitivity analysis setup and file editing well, and if you're doing many simulations parallelizing input file creation/running simulations is more important than having one setup file. I don't think manually writing sensitivity analysis parameters is the solution. 
> 
> That being said, my opinion would be that type of input should be 3 combinations of [(A=1, B=4), (A=2, B=5), (A=3, B=5)]. Not all SA use combinatorial approaches, e.g. [morris method](https://en.wikipedia.org/wiki/Morris_method). Another thing to consider is whether or not these would be run for all seeds.

_Originally posted by @cainja in https://github.com/bagherilab/ARCADE/pull/119#discussion_r1880702749_

**Comment by cainja** [comment]
I think it would be somewhat normal use case would be to run parameter sweeps but I don't think that it should be handled in ARCADE because there's too many edge cases, decisions that we would need to make to resolve it in ARCADE that are easily handled in external libraries. I vote to close this as out of scope.

**Comment by jessicasyu** [comment]
Okay, closing as out of scope!

@allison-li-1016 I don't think we have a lab protocol, but [cell-abm-pipeline](https://github.com/allen-cell-animated/cell-abm-pipeline) (which I used for `potts` simulations) has a pretty flexible setup for setting up sweeps using a combination of setup file templates, yaml configs, and manifest files. Happy to chat about that separately (maybe at a dev meeting)
