### ISSUE TITLE
Add functionality to divide voxels across a specified plane

### ISSUE THREAD

**Issue by Jannetty** [bagherilab/ARCADE#17]
Hello all, I am seeking a review on the following proposed design for adding functionality that allows for voxel division along user-specified planes.

**Proposed Plan:**
1. In src/env/location, define a `Plane` class that stores
  - a public final 3D point $(x_0, y_0, z_0)$ (an `ArrayList<Integer>` of length 3)
  - a public final 3D normal vector $(a,b,c)$ (an `ArrayList<Integer>` of length 3).
2. In src/env/PottsLocation.java define a `splitVoxels` function that takes a plane object as a parameter (instead of a direction) and splits voxels on either side of the plane. 
  - This will require a helper function to get the distance between a voxel and the plane using the equation: 
    - $d = a(x-x_0) + b(y-y_0) + c(z-z_0)$ where 
    - $(x_0, y_0, z_0)$ is the point in the plane class
    - $(a,b,c)$ is the normal vector in the plane class
    - $(x,y,z)$ is the voxel
    - if $d > 0$, the voxel is on one side of the plane, if $d < 0$ it is on the other side of the plane, if $d=0$ it is on the plane and is divided randomly to one side or the other.
3. In src/env/PottsLocation.java, add an overloaded `split` function that takes a plane object instead of a direction as a parameter.  This function will call the above-implemented `splitVoxels` using this plane as a parameter. Planes of division can now be instantiated in agents or in agent modules and passed to this `split` function.

**Additional options:**
1. I could also modify the direction enums to contain information for making plane object for each specified plane. I could then instantiate a plane when a direction is specified to split and only ever use the plane parameter `splitVoxels`. This change would let there be only one `splitVoxels` function and would allow all split logic to be contained in one `split` function rather than having two implementations (one that works with a direction and one that works with a plane). However it could decrease efficiency when dividing along one of the specified planes.
2. I could forego making a `Plane` class altogether and, instead of taking Plane objects as parameters, rely on the user to pass a plane's point and normal vector as parameters. I think it makes sense to encapsulate these descriptors in a class, but I also recognize that the plane itself is not an object in the simulation so that may be confusing.

**Specific feedback I would like:**
1. Should I make a `Plane` class?
2. Should I treat the existing direction planes the same way I will treat my new planes? I.e. consolidate the `split` logic and `splitVoxel` functions as described in Additional Option 1? (I can still do that consolidation without a Plane class).
3. Any other thoughts you may have!

Sorry I know this is really nitty gritty but I'm hoping to get some design feedback before I implement. Thank you all!

**Comment by jessicasyu** [comment]
I think a `Plane` class definitely makes sense -- I would pop it into `core.util` instead, which makes it more clear that it's not a physical thing in the simulation. You can have the `Plane` class contain the distance calculation.

A single `splitVoxels` function that takes a `Plane` instead of `Direction` + the existing `Direction` enum returning the corresponding `Plane` all sounds good as well. I wouldn't worry about the efficiency at this stage, if you want to make sure, you could do some benchmarking after it is implemented.

Two questions:

1. How will you handle the current `getDirection` functionality? Is the idea that there now  two main options: (a) `split` given only the RNG does the current default behavior of getting the direction based on shorted axis and (b) `split` given all parameters lets you specify any possible split
2. How will the `offsets` parameter be used? Is it captured in the `Plane` center point or is it used separately?

**Comment by Jannetty** [comment]
Thanks Jessica!

1. Yes I was thinking given just the RNG the split function will call the same `getDirection` method. When `getDirection` returns a direction, that direction will be used to make a plane (using parameters stored in the Direction enum) and will be passed to the split function with all the parameters. So yes the two options you described.
2. I was initially thinking of having the offset as separate so that there exists an option to provide a direction (via the enum) and an offset, but I think it would be more straightforward to make the point in the plane the offset. A proliferation module could use the `getOffset` function to get the point when making the plane, and when a plane is not specified the split function can make a plane using `getCenter` and enum parameters. So there would exist three split functions:
- `split(RNG)` : makes plane using `getCenter` and `getDirection`, passes to `split(RNG, Plane, Probability)`
- `split(RNG, Direction)` : makes a plane using getCenter and specified Direction, passes to `split(RNG, Plane, Probability)`
- `split(RNG, Plane, Probability)` : Does splitting

**Comment by jessicasyu** [comment]
Yeah, that all sounds great!

**Comment by Jannetty** [comment]
@jessicasyu When you have a minute can you take a look at the draft PR I have going? I followed the above in spirit, but added some other things that might be too much overhead (I made a point class, a vertex class, a plane container class, and a potts plane factory). I also left in all of the previous versions of split, which may be too much as well.

**Comment by jessicasyu** [comment]
@Jannetty Some quick thoughts:

- I don't think you need the `Point3D` or `Vector3D` -- we could probably just reuse MASON's `sim.util.Int3D` or `sim.util.Double3D`?
- Not sure what the purpose of the `PlaneContainer` class is?
- We probably don't need that many different `split` constructors -- maybe just the two (one with the default behavior and one with all the options) unless you need one of the intermediate versions
- You don't need the `PottsPlaneFactory`
    - You can just have the normal vectors as part of the Direction enum, rather than creating a separate map
    - The factory pattern is when you have a superclass with multiple subclasses and you want to return one of them based on the input (e.g. the different cell agent classes) -- in this case, the "factory" is just wrapping a constructor call

**Comment by Jannetty** [comment]
Resolved in #46
