### ISSUE TITLE
Add support for initialization by percentage instead of number

### ISSUE THREAD

**Issue by jessicasyu** [bagherilab/ARCADE#49]
Current `patch` initialization initializes cells based on a single number. For example:

```xml
<population id="<id>" init="N" class="<class>" />
```

will initialize N cells for the population. We want to support initializing by percentage, which would cover v2 functionality of specifying "FULL" to initialize at all locations (used for healthy cell background simulations). 

Proposal:

1. Update `PatchSeries` to parse configs in the form:

```xml
<population id="<id>" init="N%" class="<class>" />
```

as a percentage.

2. Update `PatchInputBuilder` geometry parsing to add total number of patches to the `patch` box
3. Update the `createCells` method in `PatchCellFactory` to create number of containers based on number or percentage

Adding this feature is necessary for #20.

**Comment by cainja** [comment]
Addressed by #53.
